---
- name: demo on filters/functions
  hosts: all
  tasks:
    - name: convert to uppercase
      vars: 
        greeting: "Hello Ramesh"
      ansible.builtin.debug:
        msg: "{{ greeting | upper}}"

    - name: convert to lowercase
      vars: 
        greeting: "Hello Ramesh"
      ansible.builtin.debug:
        msg: "{{ greeting | lower}}"
    
    - name: convert map to list
      vars: 
         course: 
          name: "Devops with aws"
          duration: 120 
          trainer: "shiva"
      ansible.builtin.debug:
        msg: "{{ course| dict2items }}"

    - name: check ip address
      vars:
       myip: "355.222.1.1"
      ansible.builtin.debug:
        msg: "{{ myip | ansible.utils.ipv4 }}" 