---
- name: demo on filters/functions
  hosts: all
  tasks:
    - name: convert to uppercase
      vars: 
        greeting: "Hello Ramesh"
      ansible.builtin.debug:
        msg: "{{ greeting | upper}}"

    - name: convert to lowercase
      vars: 
        greeting: "Hello Ramesh"
      ansible.builtin.debug:
        msg: "{{ greeting | lower}}"
