---
- name: demo on filters/functions
  hosts: all
  tasks:
    - name: convert to uppercase
      ansible.builtin.debug:
        msg: "Hello, World!"

    - name: convert to lowercase
      ansible.builtin.debug:
        msg: "Hello, World!"
